language: python
python:
  - "2.7"

cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=sexamples/ReadTest/ReadTest.ino
  - PLATFORMIO_CI_SRC=sexamples/SetTime/SetTime.ino

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio ci --board=uno --board=megaatmega2560 --board=esp12e