language: python
python:
  - "2.7"

cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/ReadTest/ReadTest.ino
  - PLATFORMIO_CI_SRC=examples/SetTime/SetTime.ino

install:
  - pip install -U platformio
  - platformio update

    #External libraries
  - wget https://github.com/PaulStoffregen/Time/archive/master.zip -O /tmp/Time.zip
  - unzip /tmp/Time.zip -d /tmp

script:
  - platformio ci --lib="." --lib="/tmp/Time-master" --board=uno --board=megaatmega2560 --board=esp12e